#![allow(
    let_underscore_drop,
    clippy::let_underscore_must_use,
    clippy::let_underscore_untyped,
    clippy::allow_attributes_without_reason,
    clippy::similar_names,
    clippy::single_char_lifetime_names,
    clippy::separated_literal_suffix,
    clippy::missing_docs_in_private_items,
    clippy::missing_inline_in_public_items,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc,
    clippy::min_ident_chars,
    clippy::doc_markdown,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::struct_excessive_bools,
    clippy::struct_field_names,
    clippy::cognitive_complexity,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::cast_precision_loss,
    clippy::single_match_else,
    clippy::option_if_let_else,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::unused_async,
    clippy::non_std_lazy_statics,
    clippy::many_single_char_names,
    clippy::multiple_inherent_impl,
    clippy::absolute_paths,
    clippy::missing_const_for_fn,
    clippy::print_stdout,
    clippy::unused_trait_names,
    clippy::ignored_unit_patterns,
    clippy::implicit_clone,
    clippy::return_and_then,
    clippy::future_not_send,
    clippy::items_after_statements,
    clippy::explicit_into_iter_loop,
    clippy::match_same_arms,
    clippy::if_then_some_else_none,
    clippy::equatable_if_let,
    clippy::redundant_closure_for_method_calls,
    clippy::match_wildcard_for_single_variants,
    clippy::unused_self,
    clippy::iter_over_hash_type,
    clippy::unnecessary_wraps,
    clippy::implicit_hasher,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::map_unwrap_or,
    clippy::manual_let_else,
    clippy::semicolon_outside_block,
    clippy::if_not_else,
    clippy::or_fun_call,
    clippy::bool_to_int_with_if,
    clippy::redundant_clone,
    clippy::use_self,
    clippy::needless_borrow,
    clippy::ref_option_ref,
    clippy::pub_with_shorthand,
    clippy::format_push_string,
    clippy::str_to_string,
    clippy::default_trait_access,
    clippy::indexing_slicing,
    clippy::string_slice,
    clippy::explicit_iter_loop,
    clippy::ref_option,
    clippy::manual_map,
    clippy::cloned_instead_of_copied,
    clippy::std_instead_of_core,
    clippy::try_err,
    clippy::rc_clone_in_vec_init,
    clippy::cast_lossless,
    clippy::clone_on_ref_ptr,
    clippy::default_numeric_fallback,
    clippy::cast_possible_wrap,
    clippy::useless_let_if_seq,
    reason = "Page handler orchestrates multiple systems with complex state management"
)]

pub mod accessibility;
pub mod config;
mod display;
mod display_api;
mod embedded_chrome;
pub mod events;
pub mod focus;
mod runtime;
pub mod scheduler;
pub mod selection;
pub mod snapshots;
pub mod state;
pub mod telemetry;
mod url;
