#!/usr/bin/env bash
set -euo pipefail

SPEC_URL=${1:-"https://www.w3.org/TR/css-display-3/"}
MODULE_SPEC_PATH=${2:-"crates/css/modules/display/spec.md"}
YEAR=${3:-"2025"}

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
spec_file="${root_dir}/${MODULE_SPEC_PATH}"

if [[ ! -f "${spec_file}" ]]; then
  echo "[vendor_display_spec] Spec file not found: ${spec_file}" >&2
  exit 1
fi

# Fetch spec HTML
if command -v curl >/dev/null 2>&1; then
  html="$(curl -fsSL "${SPEC_URL}")"
elif command -v wget >/dev/null 2>&1; then
  html="$(wget -q -O - "${SPEC_URL}")"
else
  echo "[vendor_display_spec] Need curl or wget" >&2
  exit 1
fi

# Note: pandoc is not required. We embed raw HTML inside spec.md; Markdown passes it through.

# Extract <body> and remove scripts/styles
body="$(printf '%s' "${html}" | awk 'BEGIN{IGNORECASE=1} /<body/{p=1} p{print} /<\/body>/{exit}')"
body="$(printf '%s' "${body}" | sed -E 's/<script[\s\S]*?<\/script>//Ig')"
body="$(printf '%s' "${body}" | sed -E 's/<style[\s\S]*?<\/style>//Ig')"

# Slice from the first numbered chapter >= 2 to the first non-numbered H2 (structural-only)
begin_idx=$(perl -0777 -e '
  undef $/; $s=<>; my $fallback=-1;
  while ($s =~ m{<h2[^>]*>(.*?)</h2>}sig) {
    my $pos = $-[0];
    my $h = $1;
    if ($h =~ m{<span[^>]*class="[^"]*secno[^"]*"[^>]*>\s*([0-9]+)\.}i) {
      my $n = $1; if ($n >= 2) { print $pos; exit }
    }
    if ($fallback < 0 && $h =~ m{^\s*([0-9]+)\.[^<]}s) { my $n=$1; if ($n>=2){ $fallback=$pos } }
  }
  if ($fallback >= 0) { print $fallback }
' <<<"${body}" || true)
# Export BEGIN_IDX early for subsequent perl
export BEGIN_IDX="${begin_idx}"

ack_idx=$(perl -0777 -e '
  undef $/; $s=<>; my $b=$ENV{BEGIN_IDX};
  if ($b eq q{}) { exit 0 }
  $s = substr($s, $b);
  # Find the first H2 that appears to be Acknowledgments (by text or id)
  while ($s =~ m{<h2[^>]*>(.*?)</h2>}sig) {
    my $pos = $-[0] + $b;
    my $h = $1;
    if ($h =~ m{acknowledg}i) { print $pos; exit }
  }
' <<<"${body}" || true)

if [[ -n "${begin_idx}" ]]; then
  body_slice="$(perl -0777 -pe 'BEGIN{ $b = $ENV{BEGIN_IDX}; $a = $ENV{ACK_IDX}; } END{}' 2>/dev/null <<<"")"
  export ACK_IDX="${ack_idx}"
  body="$(perl -0777 -e '
    $/=undef; $s=<>; $b=$ENV{BEGIN_IDX}; $a=$ENV{ACK_IDX};
    if($b eq q{}){print $s; exit};
    if($a eq q{}){$a=length($s);} 
    if($a < $b){ $a = length($s); }
    print substr($s,$b,$a-$b);
  ' <<<"${body}")"
fi

# Fallback if slicing failed and produced nearly empty content
if [[ ${#body} -lt 2000 ]]; then
  echo "[vendor_display_spec] Slice produced too little content; using full spec body." >&2
  body="$(printf '%s' "${html}" | awk 'BEGIN{IGNORECASE=1} /<body/{p=1} p{print} /<\/body>/{exit}')"
fi

# Payload is raw sliced HTML (no Markdown conversion, no table post-processing)
payload_html="${body}"

# Replace content between markers
start_marker_ps1='<!-- BEGIN VERBATIM SPEC: DO NOT EDIT BELOW. This block is auto-generated by scripts/vendor_display_spec.ps1 -->'
start_marker_sh='<!-- BEGIN VERBATIM SPEC: DO NOT EDIT BELOW. This block is auto-generated by scripts/vendor_display_spec.sh -->'
end_marker='<!-- END VERBATIM SPEC: DO NOT EDIT ABOVE. -->'

# Determine which start marker is present (ps1 preferred)
start_marker="${start_marker_ps1}"
if ! awk -v m="$start_marker" 'index($0,m){found=1} END{exit(found?0:1)}' "${spec_file}"; then
  start_marker="${start_marker_sh}"
fi

# Validate presence of markers
if ! awk -v m="$start_marker" 'index($0,m){found=1} END{exit(found?0:1)}' "${spec_file}" || \
   ! awk -v m="$end_marker" 'index($0,m){found=1} END{exit(found?0:1)}' "${spec_file}"; then
  echo "[vendor_display_spec] Markers not found in ${MODULE_SPEC_PATH}" >&2
  exit 1
fi

# Build new file by replacing content between markers (embed HTML as-is)
awk -v sm="$start_marker" -v em="$end_marker" -v payload="${payload_html//\/\\}" '
  BEGIN{in_block=0}
  {
    if(!in_block){
      print
    }
    if(index($0,sm)){
      in_block=1
      print ""
      print payload
    }
    if(index($0,em)){
      in_block=0
      print
    }
  }
' "${spec_file}" > "${spec_file}.tmp"

mv "${spec_file}.tmp" "${spec_file}"

echo "[vendor_display_spec] Updated ${MODULE_SPEC_PATH} with verbatim spec content from ${SPEC_URL}."
